# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
  - repo: https://github.com/psf/black
    rev: 24.8.0 # upgrade black version, because of the click error -> https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
    hooks:
      - id: black
        args:
          - --line-length=120
          - --include=\.src/
        exclude: ^.resources/,^.runtime/
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - "--ignore=E203, E266, E501, W503, F403, F401"
          - "--max-line-length=120"
        additional_dependencies: [ flake8-bugbear ]
        exclude: ^resources/,^runtime/,^git,^__pycache__,^pytest_cache,^mypy_cache